# GitHub Action for PHP with extensions
name: Windows

on:
  push:
    branches:
    - v5
  pull_request:
    branches:
    - v5

jobs:
  windows:
    name: Windows (PHP ${{ matrix.php-versions }} CI)
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [windows-latest]
        php-versions: ['7.1', '7.2', '7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, mysqli, pdo_mysql, pgsql, pdo_pgsql, sqlite3, pdo_sqlite, sqlsrv, pdo_sqlsrv, xdebug
          coverage: xdebug
      - name: Chocolatey Install MySQL
        run: choco install mysql --version=5.7.18 -y -f
      - name: Setup MySQL Database
        run: |
          mysql -u root -e "CREATE DATABASE IF NOT EXISTS ez_test;"
          mysql -u root -e "CREATE USER ez_test@localhost IDENTIFIED BY 'ezTest'; GRANT ALL ON ez_test.* TO ez_test@localhost; FLUSH PRIVILEGES;"
      - name: Setup PostgreSql Database
        run: |
          $env:Path += ";C:\Program Files\PostgreSQL\13\bin"
          $env:PGUSER = "postgres"
          $env:PGPASSWORD = "root"
          initdb -D "C:\Program Files\PostgreSQL\13\data"
          pg_ctl -D "C:\Program Files\PostgreSQL\13\data" -l logfile start
          psql -U postgres -c "CREATE USER ez_test WITH PASSWORD 'ezTest';" --command="\du"
          createdb --owner=ez_test ez_test
          [Environment]::SetEnvironmentVariable("Path", $env:Path, [EnvironmentVariableTarget]::Machine)
      - name: Setup SQLServer Database
        run: |
          # MSSQLLocalDB is the default SQL LocalDB instance
          SqlLocalDB start MSSQLLocalDB
          SqlLocalDB info MSSQLLocalDB
          sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "CREATE DATABASE ez_test"
          sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "EXEC sp_addlogin 'ez_test', 'ezTest', 'ez_test'"
          sqlcmd -S "(localdb)\MSSQLLocalDB" -d ez_test -Q "ALTER SERVER ROLE [sysadmin] ADD MEMBER ez_test"
      - name: Install dependencies
        run: composer update
      - name: Test with phpunit
        run: vendor\bin\phpunit --coverage-clover=coverage.xml
      - name: Submit code coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml # optional
