# GitHub Action for PHP with extensions
name: ezsql-linux

on: [push, pull_request]

jobs:
  linux:
    name: Linux (PHP ${{ matrix.php-versions }} CI)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, fileinfo, mysqli, pdo_mysql, pgsql, pdo_pgsql, sqlite3, pdo_sqlite, sqlsrv, pdo_sqlsrv, xdebug
          coverage: xdebug
      - name: Start MySQL
        run: sudo systemctl start mysql.service
      - name: Setup MySQL Database
        run: |
          mysql -uroot -h127.0.0.1 -proot -e "CREATE DATABASE IF NOT EXISTS ez_test;"
          mysql -uroot -h127.0.0.1 -proot -e "CREATE USER ez_test@localhost IDENTIFIED BY 'ezTest'; GRANT ALL ON ez_test.* TO ez_test@localhost; FLUSH PRIVILEGES;"
      - name: Start PostgreSql
        run: sudo systemctl start postgresql.service
      - name: Setup PostgreSql Database
        run: |
          export PGPASSWORD='root'; psql -h localhost -U postgres -c 'CREATE DATABASE ez_test;'
          export PGPASSWORD='root'; psql -h localhost -U postgres -c "CREATE USER ez_test WITH PASSWORD 'ezTest';"
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: localhost
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: root
          POSTGRES_USER: postgres
      - name: Setup SQLServer Database
        run: |
          # MSSQLLocalDB is the default SQL LocalDB instance
          SqlLocalDB start MSSQLLocalDB
          SqlLocalDB info MSSQLLocalDB
          sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "CREATE DATABASE ez_test"
          sqlcmd -S "(localdb)\MSSQLLocalDB" -Q "CREATE LOGIN ez_test WITH PASSWORD=N'ezTest', DEFAULT_DATABASE=ez_test, CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF; ALTER SERVER ROLE [sysadmin] ADD MEMBER ez_test"
      - name: Install dependencies
        run: composer install --no-progress
      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-clover
      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)
